language: android
dist: trusty
before_install:
    - chmod +x gradlew
android:
    components:
        - build-tools-28.0.2
        - android-28
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository