language: android
dist: trusty

android:
    components:
        - tools
        - build-tools-28.0.2
        - android-28
        - platform-tools
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
script:
    - chmod +x gradlew
    - ./gradlew androidDependencies
    - ./gradlew lint test
