language: android
dist: trusty

android:
    components:
        - tools
        - build-tools-28.0.2
        - android-28
        - platform-tools
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
jobs:
    include:
        - stage: chmod permissions
          name : Permissions
          script: "- chmod +x gradlew"
        - stage: Download Dependencies
          name: Dependencies
          script: "/gradlew androidDependencies"
        - stage: Run tests
          name: Test
          script: "./gradlew lint test"